<?php
/*
	事先下面导入数据
	SELECT ins_date,guid,server_id,cash,pay_type,sdk FROM `pay_orders` where ins_date between '2016-11-16' and '2016-12-19' and server_id like 'android%' and sdk!='FULI'

*/
//ob_start();
$log_path = "/root/logs/crontab/LVT.log";
try
{
	$hw_date=shell_exec("hwclock -r");
	$hw_date=substr($hw_date,0,24);
}
catch( Exception  $e ) 
{
	print $e->getMessage();
	$hw_date = "";
}


date_default_timezone_set('Asia/Shanghai');
$route_server_group=[
		'androids1' =>[
					'host'      => '123.207.146.159',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',
				],
		'androids2' =>[
					'host'      => '123.207.141.241',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',
				],
		'androids3' =>[
					'host'      => '123.206.44.246',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',
				],
		'androids4' =>[
					'host'      => '123.207.167.15',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',
				],
		];
$server_group=[
		'androids1' =>[
					'host'      => '123.207.146.159',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids2' =>[
					'host'      => '123.207.141.241',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids3' =>[
					'host'      => '123.206.44.246',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids4' =>[
					'host'      => '123.207.167.15',
					'database'  => 'fightwar_log_0004',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0004","log"=>"fightwar_log_0004",
				],
		'androids5' =>[
					'host'      => '123.206.78.130',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids6' =>[
					'host'      => '123.207.156.70',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids7' =>[
					'host'      => '123.207.167.166',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids8' =>[
					'host'      => '123.207.159.121',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids9' =>[
					'host'      => '123.207.159.95',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids10' =>[
					'host'      => '123.207.157.20',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids11' =>[
					'host'      => '123.206.50.89',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
 					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids12' =>[
					'host'      => '123.207.159.136',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
 					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
 				],
		'androids13' =>[
 					'host'      => '123.207.166.207',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
 					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
 				],
		'androids14' =>[ 
					'host'      => '123.206.76.74',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
 					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
 				],
		'androids15' =>[ 
					'host'      => '123.207.170.225',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
 					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
 				],
		'androids16' =>[ 
					'host'      => '139.199.22.141',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
 					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
 				],
		'androids17' =>[ 
					'host'      => '123.206.26.202',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
 					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
 				],
				
		'androids18' =>[ 
					'host'      => '123.207.143.202',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
 					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
 				],
		'androids19' =>[ 
					'host'      => '123.206.66.235',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
 					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
 				],
		'androids20' =>[
					'host'      => '123.206.23.211',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids21' =>[
					'host'      => '123.206.25.137',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids22' =>[
					'host'      => '123.206.13.159',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids23' =>[
					'host'      => '123.207.142.179',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids24' =>[
					'host'      => '123.206.50.118',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'port'    => '10529',"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids25' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.58.143',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids26' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.165.53',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids27' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.87.130',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids28' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.164.151',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids29' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.167.62',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids30' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.95.143',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids31' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.161.218',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids32' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.75.212',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids33' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.74.39',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids34' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.91.167',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids35' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.153.136',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids36' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.145.248',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids37' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.14.195',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids38' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.20.198',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids39' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.172.183',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids40' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.13.47',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
				
		'androids41' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.18.170',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids42' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.88.104',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids43' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.34.135',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids44' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.169.44',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids45' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.23.182',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids46' =>[
					'driver'    => 'mysql',
					'host'      => '139.199.98.163',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids47' =>[
					'driver'    => 'mysql',
					'host'      => '139.199.99.96',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids48' =>[
					'driver'    => 'mysql',
					'host'      => '139.199.97.115',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids49' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.15.229',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids50' =>[
					'driver'    => 'mysql',
					'host'      => '139.199.97.62',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],

		'androids51' =>[
					'driver'    => 'mysql',
					'host'      => '118.89.228.196',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids52' =>[
					'driver'    => 'mysql',
					'host'      => '118.89.234.248',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids53' =>[
					'driver'    => 'mysql',
					'host'      => '118.89.233.119',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids54' =>[
					'driver'    => 'mysql',
					'host'      => '118.89.233.209',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids55' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.78.130',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids56' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.156.70',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids57' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.167.166',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids58' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.159.121',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids59' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.159.95',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids60' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.157.20',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids61' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.50.89',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids62' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.159.136',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids63' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.166.207',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids64' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.76.74',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids65' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.170.225',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids66' =>[
					'driver'    => 'mysql',
					'host'      => '139.199.22.141',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids67' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.26.202',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids68' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.143.202',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids69' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.66.235',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids70' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.23.211',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids71' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.25.137',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids72' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.13.159',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids73' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.142.179',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids74' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.50.118',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids75' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.58.143',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids76' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.165.53',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids77' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.87.130',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids78' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.164.151',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids79' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.167.62',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids80' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.95.143',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids81' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.161.218',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids82' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.75.212',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids83' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.74.39',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids84' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.91.167',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids86' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.145.248',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids87' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.14.195',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids88' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.20.198',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids89' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.172.183',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids90' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.13.47',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids91' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.18.170',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids92' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.88.104',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids93' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.34.135',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids94' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.169.44',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids95' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.23.182',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids96' =>[
					'driver'    => 'mysql',
					'host'      => '139.199.98.163',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids97' =>[
					'driver'    => 'mysql',
					'host'      => '139.199.99.96',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids98' =>[
					'driver'    => 'mysql',
					'host'      => '139.199.97.115',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids99' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.15.229',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids100' =>[
					'driver'    => 'mysql',
					'host'      => '139.199.97.62',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids101' =>[
					'driver'    => 'mysql',
					'host'      => '118.89.228.196',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids102' =>[
					'driver'    => 'mysql',
					'host'      => '118.89.234.248',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids103' =>[
					'driver'    => 'mysql',
					'host'      => '118.89.233.119',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids104' =>[
					'driver'    => 'mysql',
					'host'      => '118.89.233.209',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],
		'androids106' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.78.130',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids107' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.156.70',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids108' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.167.166',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids109' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.159.121',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids105' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.159.95',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids110' =>[
			'driver'    => 'mysql',
			'host'      => '123.207.157.20',
			'database'  => 'fightwar_log_0001',
			'username'  => 'root',
			'password'  => 'yuzuki',
			'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'port'    => '10529',
            "account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
		],
		'androids111' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.50.89',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids112' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.159.136',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids113' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.166.207',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids114' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.76.74',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids115' =>[
					'driver'    => 'mysql',
					'host'      => '139.199.22.141',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids116' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.26.202',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids117' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.143.202',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids118' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.66.235',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],
		'androids119' =>[
					'driver'    => 'mysql',
					'host'      => '123.206.23.211',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login","main"=>"fightwar_main_0001","log"=>"fightwar_log_0001",
				],

		'androids85' =>[
					'driver'    => 'mysql',
					'host'      => '123.207.153.136',
					'database'  => 'fightwar_log_0001',
					'username'  => 'root',
					'password'  => 'yuzuki',
					'charset'   => 'utf8',
					'collation' => 'utf8_unicode_ci',
					'prefix'    => '',
					'port'    => '10529',
					"account"=>"fightwar_login_0002","main"=>"fightwar_main_0002","log"=>"fightwar_log_0002",
				],				
	];
$channal_group = [
				"UC"=>"UC","QIHOO360"=>"360",
				
				"XIAOMI"=>"XIAOMI","PEAPODS"=>"PEAPODS","GIONEE"=>"GIONEE","BAIDU"=>"BAIDU",
				"HUAWEI"=>"HUAWEI","LENOVO"=>"LENOVO","COOLPAD"=>"COOLPAD","MEIZU"=>"MEIZU","VIVO"=>"VIVO","OPPO"=>"OPPO",
				"TT"=>"TT","4399"=>"4399","DCN"=>"当乐","QQ"=>"QQ","HOLA"=>"HOLA","PYW"=>"PYW",
				"ANZHI"=>"ANZHI","MZW"=>"MZW","IQIYI"=>"IQIYI","LETV"=>"LETV","QQWX"=>"微信",
				"XIAO7"=>"XIAO7","AHAIMA"=>"安卓海马",
				//
				"PP"=>"PP","XY"=>"XY","I4"=>"I4","TBT"=>"TBT","KUAIYONG"=>"KUAIYONG","HAIMA"=>"HAIMA"
				
			];
$today = date("Y-m-d");
print $today."\n";
$start_stamp = strtotime("$today-1day");
$start_date = date("Y-m-d H:i:s",$start_stamp);
$end_stamp = strtotime($today) ;
$end_date = date("Y-m-d H:i:s",$end_stamp);
$script_start_stamp=time();

$guid_arr=array();
$guid_str = "";

$local_db = new PDO("mysql:host=139.129.21.196;dbname=fightwar_admin","root","123qwe",array(PDO::ATTR_PERSISTENT => true,PDO::MYSQL_ATTR_INIT_COMMAND => "set names utf8")) or die("fail to login $k");
/*
	账号导入 new_account 表
*/
$query = "LOAD DATA INFILE '/root/insert_data.sql' INTO TABLE new_account 	(`account`,`creationdate`)";
$local_db ->exec($query);
$local_db = null ;
die;
foreach ($server_group as $k=>$v)
{
	echo "serverID : $k ";
	file_put_contents("vip_role.csv"," \n",FILE_APPEND) ;
	$pdo = new PDO("mysql:host={$v["host"]};port={$v["port"]};dbname={$v["database"]}","root","yuzuki",array(PDO::ATTR_PERSISTENT => true,PDO::MYSQL_ATTR_INIT_COMMAND => "set names utf8")) or die("fail to login $k");
	//$pdo -> exec('set names utf-8');
	
	$account_query= "select account,from_unixtime(creationdate,'%Y-%m-%d') as creationdate from {$v["account"]}.Global_Account ";
	$account_class=$pdo->query($account_query);
	
	if(is_bool($account_class)){
		print "no payer in $k";
		print "\n";
		continue;
		}
	$account_class->setFetchMode(PDO::FETCH_ASSOC);
	$account_query_data=$account_class->fetchall();
	foreach($account_query_data as $kd=>$vd)
	{
		file_put_contents(date("YmdH")."account_data.csv","{$vd['account']} \t {$vd['creationdate']} \r\n",FILE_APPEND);
	}

	$pdo = $query_class= null;
	$script_stamp=time();
	
	print " in ".($script_stamp-$script_start_stamp)." sec \n";
}
/*
	pay_orders 表更新用户创角时间
*/
/*
foreach ($server_group as $k=>$v)
{
	echo "serverID : $k ";
	file_put_contents("vip_role.csv","serverID : $k \n",FILE_APPEND) ;
	$pdo = new PDO("mysql:host={$v["host"]};port={$v["port"]};dbname={$v["database"]}","root","yuzuki",array(PDO::ATTR_PERSISTENT => true,PDO::MYSQL_ATTR_INIT_COMMAND => "set names utf8")) or die("fail to login $k");
		//$pdo -> exec('set names utf-8');
	
	$query_payer_guid= "select guid from fightwar_admin.pay_orders where server_id = '$k'  ";
	$payer_guid_class=$local_db->query($query_payer_guid);
	//var_dump($query_payer_guid,$payer_guid_class);die;
	if(is_bool($payer_guid_class)){
		print "no payer in $k";
		print "\n";
		continue;
		}
	$payer_guid_class->setFetchMode(PDO::FETCH_ASSOC);
	$payer_guid_query_data=$payer_guid_class->fetchall();//var_dump($payer_guid_query_data);die;
	
	foreach($payer_guid_query_data as $kd=>$vd)
	{
		$guid_arr[]=$vd["guid"];
	}
	$guid_str = "(".implode(",",$guid_arr).")";
	
	$query_payer_name = "select aa.guid,bb.creationdate from (select * from {$v["main"]}.Player_Character where guid in $guid_str )as aa JOIN {$v["account"]}.Global_Account as bb ON aa.AccountID = bb.AccountID";
	$payer_name_class = $pdo -> query($query_payer_name);
	//var_dump($query_payer_name,$payer_name_class);die;
	if(is_bool($payer_name_class)){
		print "no such account";
		print "\n";
		continue;
		}
	$payer_name_class->setFetchMode(PDO::FETCH_ASSOC);
	$payer_name_data=$payer_name_class->fetchall();//var_dump($payer_name_data);die;
	foreach( $payer_name_data as $nk=>$nv )
	{
		$query_update = "update fightwar_admin.pay_orders set `registdate`=from_unixtime({$nv["creationdate"]},'%Y-%m-%d') where server_id = '$k' and guid = {$nv["Guid"]}";
		//var_dump($query_update);die;
		$local_db->exec($query_update);
	}
	$pdo = $query_class= null;
	$script_stamp=time();
	
	print " in ".($script_stamp-$script_start_stamp)." sec \n";
}
$local_db = null;
*/
//SELECT ins_date,sum(cash) FROM `pay_orders` where sdk = 'UC' and ins_date > '2017-01-26' and account in (select account from fightwar_admin.new_account where creationdate = '2017-02-05' and sdk = 'UC') group BY ins_date
function vip9 ()
{
	$query_dau = "SELECT
							ct.guid,
							ct. NAME,
							ct.vip,
							role.ruid,
							role.NAME as uname,
							role.level,
							role.color,
							role.star,
							role.washcount,
							role.skilllevel
						FROM
							fightwar_main_0001.Player_Character AS ct
						RIGHT JOIN fightwar_main_0001.Player_Role AS role ON ct.guid = role.guid
						WHERE
							vip > 8
						AND ct.guid IN (
							SELECT
								guid
							FROM
								fightwar_log_0001.Log_Record_3
							where
								creationdate > '2016-12-02'
						)
						ORDER BY
							Guid
				";
if(is_bool($dau_class)){
				continue;
				}
			$dau_class->setFetchMode(PDO::FETCH_ASSOC);
			$dau_query_data=$dau_class->fetchall();//var_dump($dau_query_data);die;
			foreach($dau_query_data as $kd=>$vd)
			{
				file_put_contents("vip_role.csv",
					"guid:{$vd["guid"]},name:{$vd["NAME"]},vip:{$vd["vip"]},hero:{$vd["uname"]},level:{$vd["level"]},品质:{$vd["color"]},星级:{$vd["star"]},技能:{$vd["skilllevel"]},养成次数:{$vd["washcount"]},\n",
					FILE_APPEND) ;
			}
	
		$pdo = $query_class= null;
		$script_stamp=time();
		print " in ".($script_stamp-$script_start_stamp)." sec \n";				
}
//{"id":81073,"num":3},{"id":70023,"num":15},{"id":31006,"num":3},{"id":85206,"num":13},{"id":81190,"num":1},{"id":82030,"num":2},{"id":89001,"num":7},{"id":81140,"num":1},{"id":81195,"num":1},{"id":82072,"num":1},{"id":81130,"num":1},{"id":81142,"num":2},{"id":82081,"num":1},{"id":81083,"num":3},{"id":83080,"num":2},{"id":81191,"num":1},{"id":81192,"num":1},{"id":51070,"num":1},{"id":20001,"num":1},{"id":83042,"num":1},{"id":81081,"num":2},{"id":89011,"num":1},{"id":81193,"num":1}]